paper_rock_sissors_statistics:
    resource: "@PaperRockSissorsBundle/Resources/config/routing/statistics.yml"
    prefix:   /statistics

paper_rock_sissors_homepage:
    path:     /
    defaults: { _controller: PaperRockSissorsBundle:Default:index }

paper_rock_sissors_play:
    path:     /{state}
    defaults: { _controller: PaperRockSissorsBundle:Default:play }
